// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Code string `json:"code"`
}

type InfoRequest struct {
}

type InfoResponse struct {
	Token  string `json:"token"`
	Amount uint   `json:"amount"`
}

type ReportRequest struct {
	Content string `json:"content"`
}

type ReportResponse struct {
	Data string `json:"data"`
}

type ImageRequest struct {
	Content string `json:"content"`
}

type ImageResponse struct {
	Url string `json:"url"`
}

type WatermarkRequest struct {
	Url      string  `json:"url"`
	Content  string  `json:"content"`
	Position string  `json:"position"`
	Opacity  float32 `json:"opacity"`
	FontSize uint    `json:"fontSize"`
	Color    string  `json:"color"`
}
